---
- hosts: me
  vars_files:
  - vars/main.yml
  - vars/personal.yml
  vars:
  - ansible_become_pass: "{{ sudopassword }}"
  become: true
  become_method: sudo
  tasks:
  - name: Update apt cache.
    apt: update_cache=yes cache_valid_time=86400

  - name: Ensure required packages are installed.
    apt: 
      pkg:
        - git-core
        - curl
        - zlib1g-dev
        - build-essential
        - libssl-dev
        - libreadline-dev
        - libyaml-dev
        - libsqlite3-dev
        - sqlite3
        - libxml2-dev
        - libxslt1-dev
        - libcurl4-openssl-dev
        - libffi-dev
      state: present
      
  - name: Ensure base applications are installed.
    apt:
      pkg:
        - git
        - gimp
        - blender
        - inkscape
        - vlc
        - filezilla
        - geany
        - chromium-browser
        - scribus
        - gufw
      state: present