---
- hosts: me
  vars_files:
  - vars/main.yml
  - vars/personal.yml
  vars:
  - ansible_become_pass: "{{ sudopassword }}"
  become: true
  become_method: sudo

  tasks:
  - name: Update apt cache.
    apt: update_cache=yes cache_valid_time=86400

  roles:
  # Essential roles.
  - { role: geerlingguy.firewall }
  - { role: geerlingguy.apache, tags: ['webserver']}
  - { role: geerlingguy.apache-php-fpm, tags: ['webserver'] }
  - { role: geerlingguy.php, tags: ['php'] }
  - { role: geerlingguy.php-pecl, tags: ['php'] }
  - { role: geerlingguy.composer, tags: ['php'] }
  - { role: geerlingguy.mysql, tags: ['database'] }
  - { role: geerlingguy.php-mysql, tags: ['php', 'database'] }


  # Conditionally-installed roles.
  - { role: geerlingguy.drupal-console, tags: ['drupal']}
  
  #  tags: ['php']
  - role: geerlingguy.php-xdebug
    tags: ['php', 'xdebug']
  - role: thom8.php-upload-progress
    tags: ['php']

  - { role: geerlingguy.adminer, tags: ['database'] }
  - { role: geerlingguy.pimpmylog }
  - { role: geerlingguy.nodejs }
  - { role: geerlingguy.ruby }