---
- hosts: me
  sudo: yes
  tasks:
  - name: Update apt cache.
    apt: update_cache=yes cache_valid_time=86400

  - name: Ensure MySQL is installed.
    apt: "name={{ item }} state=installed"
    with_items:
      - mysql-common
      - mysql-server

    notify: restart webserver
