---
- hosts: me
  sudo: yes
  tasks:
  - name: Update apt cache.
    apt: update_cache=yes cache_valid_time=86400

  - name: Ensure base applications are installed.
    apt: "name={{ item }} state=installed"
    with_items:   
      - git
      - gimp 
      - blender
      - inkscape
      - vlc
      - filezilla
      - geany
      - chromium-browser
      - scribus
