---
- hosts: me
  sudo: yes
  tasks:
  - name: Update apt cache.
    apt: update_cache=yes cache_valid_time=86400

  - name: Ensure MySQL is installed.
    apt: "name={{ item }} state=installed"
    with_items:
      - mysql-common
      - mysql-server

  - name: Ensure Apache is installed.
    apt: "name={{ item }} state=installed"
    with_items: 
      - apache2
      - apache2-utils

  - name: Enable Apache rewrite module.
    apache2_module: name=rewrite state=present
    notify: restart apache

  - name: Ensure PHP packages are installed.
    apt:
      name: "{{ item }}"
      state: installed
    with_items:   
      - php5
      - libapache2-mod-php5
      - php5-mcrypt
      - php5-cli
      - php5-common
      - php5-curl
      - php5-dev
      - php5-fpm
      - php5-gd
      - php-pear
      - php-apc
      - libpcre3-dev
    notify: restart webserver

  - name: Ensure Ruby is installed
    apt: "name={{ item }} state=installed"
    with_items: 
      - git-core 
      - curl 
      - zlib1g-dev 
      - build-essential 
      - libssl-dev 
      - libreadline-dev 
      - libyaml-dev
      - libsqlite3-dev
      - sqlite3
      - libxml2-dev 
      - libxslt1-dev 
      - libcurl4-openssl-dev 
      - python-software-properties 
      - libffi-dev
