galaxy_info:
  role_name: ssl
  author: Damian Lewis
  description: Generates self-signed SSL certificates.
  license: BSD

  min_ansible_version: 2.5

  platforms:
  - name: Ubuntu
    versions:
    - trusty
    - xenial
    - bionic

  galaxy_tags:
  - certificates
  - encryption
  - https
  - networking
  - ssl
  - web

dependencies: []
