---
# tasks file for andyhat-php
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Ensure PHP packages are installed.
  apt:
    name: "{{ item }}"
    state: installed
  with_items:
    - php
    - libapache2-mod-php
    - php-mcrypt
    - php-cli
    - php-common
    - php-curl
    - php-dev
    - php-fpm
    - php-gd
    - php-pear
    - libpcre3-dev
  notify: restart webserver
